### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Clindbergh** [matkoch/rider-playground#1]
Hi

It would be great if you could push your current version of the playground as used in the presentation tonight. 
Thanks for the presentation btw 👍.

Cheers

**Comment by matkoch** [comment]
are you missing anything specific? I don't have any pending commits to push

**Comment by Clindbergh** [comment]
Sorry, I missed it. I was under the impression, that the repository was outdated because the readme looks like it was just a template yet to be adapted and most files are updated more than a year ago. However the solution works just fine 👍 .

To demonstrate language injection with SQL I've added the [Northwind Sample Database (sqlite)](https://github.com/jpwhite3/northwind-SQLite3/blob/master/Northwind_small.sqlite) to the solution. If you consider this a useful addition, I am happy to make a Pull request.
